export const manualCopy = {
  ru: {
    add: 'Добавить поездку', title: 'Дорога, которую помнишь', intro: 'Добавьте поездку, которую не записали на телефоне.', back: 'Мои поездки',
    checkingAvailability: 'Проверяем доступность…', availableSoon: 'Добавление поездок появится позже', availableSoonBody: 'Пока здесь можно просматривать поездки, синхронизированные с iPhone.', temporarilyUnavailable: 'Добавление поездок пока недоступно. Черновик остался на этом экране.',
    pro: 'Ручные поездки с PRO', proBody: 'Соберите маршрут на большой карте — он появится в вашей истории и синхронизируется с iPhone. Для добавления нужна активная подписка TripTrack PRO.', proHint: 'Оформите или восстановите PRO в приложении, войдя в тот же аккаунт, затем обновите статус здесь.', check: 'Проверить подписку', checking: 'Проверяем PRO…', proActive: 'PRO активен', proLost: 'Подписка сейчас не подтверждена. Черновик на месте: обновите статус перед сохранением.',
    routeStep: 'Маршрут', detailsStep: 'Детали поездки', roads: 'По дорогам', draw: 'Точками', drawHint: 'Точки соединяются напрямую. Отметьте повороты, чтобы повторить свой путь.', roadsHint: 'Укажите начало и конец. Добавляйте промежуточные точки, чтобы уточнить дорогу.', noProvider: 'Прокладка по дорогам пока недоступна. Маршрут можно нарисовать точками на карте.', providerError: 'Поиск и прокладка временно недоступны. Рисование точками работает.', search: 'Город, адрес или координаты', coordinateSearch: 'Координаты: 45.04, 38.97', searchLabel: 'Найти место или координаты', searchAction: 'Найти', searching: 'Ищем…', noPlaces: 'Ничего не нашли. Уточните адрес или выберите точку на карте.', coordinatesHint: 'Можно ввести широту и долготу через запятую.', point: 'Точка', start: 'Начало', finish: 'Финиш', addMap: 'Нажмите на карту, чтобы добавить точку', drag: 'Точки можно перетаскивать на карте.', reverse: 'Развернуть маршрут', undo: 'Убрать последнюю точку', clear: 'Очистить', fit: 'Показать весь маршрут', remove: 'Удалить точку', up: 'Выше', down: 'Ниже', focus: 'Показать точку на карте', pointLimit: 'Достигнут предел точек для этого режима.', building: 'Прокладываем маршрут…', routeFailed: 'Не удалось проложить дорогу между точками. Попробуйте подвинуть их ближе к дороге или выберите режим «Точками».', retryRoute: 'Построить ещё раз', ready: 'Маршрут готов', routeNeeded: 'Добавьте минимум две точки', distance: 'Расстояние', estimated: 'Ориентир по времени', next: 'Далее: дата и машина', previous: 'Изменить маршрут',
    tripTitle: 'Название поездки', titlePlaceholder: 'Например, выходные у моря', when: 'Когда выехали', timeZone: 'Время вашего браузера', duration: 'Сколько ехали', hours: 'Часы', minutes: 'Минуты', useEstimate: 'Взять время маршрута', vehicle: 'Машина', noVehicle: 'Без машины', vehiclesError: 'Не удалось загрузить гараж.', vehicleRetry: 'Загрузить ещё раз', review: 'Проверьте перед сохранением', private: 'Поездку будете видеть только вы. Поделиться ею можно позже в приложении.', manualNote: 'Это ручная поездка: километры войдут в историю, а опыт и награды за GPS-запись не начисляются.', save: 'Сохранить поездку', saving: 'Сохраняем…', saved: 'Ещё одна дорога в истории', savedBody: 'Поездка сохранена. На iPhone она появится после синхронизации в том же аккаунте.', open: 'Открыть поездку', another: 'Добавить ещё одну', exitTitle: 'Оставить черновик?', exitBody: 'Этот маршрут ещё не сохранён. Если уйти, его придётся собрать заново.', stay: 'Продолжить редактирование', leave: 'Уйти', uncertain: 'Не удалось подтвердить сохранение. Повторите отправку: та же поездка не создастся дважды. До подтверждения черновик защищён от изменений.', retrySave: 'Повторить сохранение',
    title_error: 'Дайте поездке название — до 200 символов.', route_error: 'Нужен маршрут длиной хотя бы 10 метров.', date_error: 'Укажите прошедшую дату в пределах последних 20 лет.', duration_error: 'Длительность — от минуты до семи дней.', end_error: 'Поездка должна закончиться к настоящему времени.', speed_error: 'Для такой дороги нужно больше времени: средняя скорость превышает 180 км/ч.',
    providerCredit: 'Поиск и маршруты: Geoapify / OpenStreetMap', providerPrivacy: 'При поиске адрес и выбранные точки передаются картографическому сервису.', confirmClear: 'Очистить все точки маршрута?', cancel: 'Отмена', invalidCoordinate: 'Введите координаты в формате 45.04, 38.97 или выберите точку на карте.', unknownError: 'Не удалось выполнить запрос. Попробуйте ещё раз.', homePrivacy: 'Домашняя зона с iPhone здесь не применяется. Проверьте начало и конец маршрута перед сохранением.', pro_required: 'Для сохранения нужна активная PRO. Черновик сохранён на этом экране.', vehicle_missing: 'Машина больше недоступна. Выберите другую или «Без машины».', id_conflict: 'Не удалось сохранить с этим номером поездки. Откройте историю и проверьте, нет ли её там.', routeUnconfigured: 'Прокладка по дорогам ещё не подключена.', noRoute: 'Дорога между этими точками не найдена.', clearDraft: 'Маршрут очищен',
  },
  en: {
    add: 'Add a trip', title: 'A road you remember', intro: 'Add a drive you didn’t record on your phone.', back: 'My trips',
    checkingAvailability: 'Checking availability…', availableSoon: 'Adding trips is coming later', availableSoonBody: 'For now, you can explore the trips synced from your iPhone here.', temporarilyUnavailable: 'Adding trips is unavailable for now. Your draft is still on this screen.',
    pro: 'Manual trips with PRO', proBody: 'Build a route on a big map. It will join your history and sync to your iPhone. Adding trips requires an active TripTrack PRO subscription.', proHint: 'Subscribe or restore PRO in the app using the same account, then refresh your status here.', check: 'Check subscription', checking: 'Checking PRO…', proActive: 'PRO is active', proLost: 'Your subscription isn’t confirmed right now. Your draft is still here: refresh your status before saving.',
    routeStep: 'Route', detailsStep: 'Trip details', roads: 'Follow roads', draw: 'Draw points', drawHint: 'Points connect directly. Mark the turns to recreate your drive.', roadsHint: 'Choose the start and finish. Add stops to refine the road.', noProvider: 'Road routing is not available yet. You can draw the route with points on the map.', providerError: 'Search and routing are temporarily unavailable. You can still draw points.', search: 'City, address or coordinates', coordinateSearch: 'Coordinates: 45.04, 38.97', searchLabel: 'Find a place or coordinates', searchAction: 'Find', searching: 'Searching…', noPlaces: 'No places found. Refine the address or choose a point on the map.', coordinatesHint: 'You can enter latitude and longitude, separated by a comma.', point: 'Point', start: 'Start', finish: 'Finish', addMap: 'Click the map to add a point', drag: 'Drag points on the map to move them.', reverse: 'Reverse route', undo: 'Remove last point', clear: 'Clear', fit: 'Fit route to map', remove: 'Remove point', up: 'Move up', down: 'Move down', focus: 'Show point on map', pointLimit: 'You’ve reached the point limit for this mode.', building: 'Finding the road…', routeFailed: 'Couldn’t find a road between these points. Move them closer to a road or choose Draw points.', retryRoute: 'Try routing again', ready: 'Route ready', routeNeeded: 'Add at least two points', distance: 'Distance', estimated: 'Estimated time', next: 'Next: date and car', previous: 'Edit route',
    tripTitle: 'Trip name', titlePlaceholder: 'For example, a weekend by the sea', when: 'When you left', timeZone: 'Your browser’s local time', duration: 'Time on the road', hours: 'Hours', minutes: 'Minutes', useEstimate: 'Use route estimate', vehicle: 'Car', noVehicle: 'No car', vehiclesError: 'Couldn’t load your garage.', vehicleRetry: 'Load again', review: 'Check before saving', private: 'Only you will see this trip. You can share it later in the app.', manualNote: 'This is a manual trip: kilometres join your history, but it earns no GPS recording experience or badges.', save: 'Save trip', saving: 'Saving…', saved: 'Another road in your story', savedBody: 'Your trip is saved. It will appear on your iPhone after syncing with the same account.', open: 'Open trip', another: 'Add another trip', exitTitle: 'Leave this draft?', exitBody: 'This route hasn’t been saved. If you leave, you’ll need to build it again.', stay: 'Keep editing', leave: 'Leave', uncertain: 'We couldn’t confirm the save. Send it again: the same trip won’t be created twice. Your draft is locked until we know the result.', retrySave: 'Retry saving',
    title_error: 'Give your trip a name, up to 200 characters.', route_error: 'The route must be at least 10 metres long.', date_error: 'Choose a past date within the last 20 years.', duration_error: 'Duration must be between one minute and seven days.', end_error: 'The trip must have finished by now.', speed_error: 'Allow more time for this route: the average speed is over 180 km/h.',
    providerCredit: 'Search and routes: Geoapify / OpenStreetMap', providerPrivacy: 'Search addresses and chosen points are sent to the map service.', confirmClear: 'Clear all route points?', cancel: 'Cancel', invalidCoordinate: 'Enter coordinates such as 45.04, 38.97 or choose a point on the map.', unknownError: 'The request failed. Please try again.', homePrivacy: 'Your iPhone’s home privacy zone is not applied here. Check the start and end of your route before saving.', pro_required: 'An active PRO subscription is required to save. Your draft is still on this screen.', vehicle_missing: 'This car is no longer available. Choose another or No car.', id_conflict: 'Couldn’t save with this trip ID. Open your history and check whether it already exists.', routeUnconfigured: 'Road routing has not been connected yet.', noRoute: 'No road found between these points.', clearDraft: 'Route cleared',
  },
} as const;
